services:
  web:
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - SECRET_KEY=ehwuvyuvy3uiy4bycbiy4ub
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis

  redis:
    image: redis:6
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  static_volume: